[package]
name = "codama-visitors-core"
description = "Core visitor framework for traversing and transforming Codama IDL node trees"
version = "0.9.2"
repository = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[dependencies]
codama-nodes = { version = "0.9.2", path = "../codama-nodes" }

[dev-dependencies]
serde_json = "1.0"
pretty_assertions = "1.4.1"
