//! Cross-language conformance tests: verify the Rust visitors against fixtures
//! produced by the real upstream `@codama/visitors` (TypeScript).
//!
//! `fixtures/visitors.json` holds `{ visitor, label, args, input, expected }`
//! cases generated by `fixtures/generate.mjs` (see that file for how to
//! regenerate). For each case we parse `input` and `expected` into a Rust
//! `RootNode`, run the matching Rust visitor decoded from `args`, and compare
//! the result structurally — so the Rust port must produce the same tree the
//! TypeScript visitor did.
//!
//! Comparing parsed `RootNode`s (not raw JSON) is deliberate: `serde` omits
//! default/empty fields on serialization, so a string compare would diverge
//! even when the trees are identical.

use codama_nodes::{NodeTrait, RootNode};
use codama_visitors::{
    update_accounts, update_defined_types, AccountUpdate, DefinedTypeUpdate, TransformVisitor,
};
use pretty_assertions::assert_eq;
use serde::Deserialize;
use serde_json::Value;

#[derive(Deserialize)]
struct Case {
    visitor: String,
    label: String,
    args: Value,
    input: Value,
    expected: Value,
}

#[test]
fn matches_upstream_typescript_visitors() {
    let cases: Vec<Case> =
        serde_json::from_str(include_str!("fixtures/visitors.json")).expect("parse fixtures");
    assert!(!cases.is_empty(), "no conformance fixtures found");

    for case in &cases {
        let id = format!("{}/{}", case.visitor, case.label);
        let input = RootNode::from_json(&case.input.to_string())
            .unwrap_or_else(|e| panic!("[{id}] failed to parse input: {e}"));
        let expected = RootNode::from_json(&case.expected.to_string())
            .unwrap_or_else(|e| panic!("[{id}] failed to parse expected: {e}"));

        let actual = run(&case.visitor, &case.args, input);
        assert_eq!(actual, expected, "conformance mismatch in case `{id}`");
    }
}

/// Dispatches a fixture's `visitor` + `args` to the equivalent Rust visitor.
fn run(visitor: &str, args: &Value, input: RootNode) -> RootNode {
    match visitor {
        "updateAccounts" => update_accounts(account_updates(args)).visit_root(input),
        "updateDefinedTypes" => update_defined_types(defined_type_updates(args)).visit_root(input),
        other => panic!("conformance harness has no Rust mapping for visitor `{other}`"),
    }
}

fn account_updates(args: &Value) -> Vec<(String, AccountUpdate)> {
    object(args)
        .iter()
        .map(|(selector, update)| {
            let mut u = AccountUpdate::new();
            if let Some(name) = str_field(update, "name") {
                u = u.name(name);
            }
            if let Some(size) = update.get("size").and_then(Value::as_u64) {
                u = u.size(size);
            }
            if is_delete(update) {
                u = u.delete();
            }
            for (from, to) in renames(update) {
                u = u.rename(from, to);
            }
            (selector.clone(), u)
        })
        .collect()
}

fn defined_type_updates(args: &Value) -> Vec<(String, DefinedTypeUpdate)> {
    object(args)
        .iter()
        .map(|(selector, update)| {
            let mut u = DefinedTypeUpdate::new();
            if let Some(name) = str_field(update, "name") {
                u = u.name(name);
            }
            if is_delete(update) {
                u = u.delete();
            }
            for (from, to) in renames(update) {
                u = u.rename(from, to);
            }
            (selector.clone(), u)
        })
        .collect()
}

fn object(value: &Value) -> &serde_json::Map<String, Value> {
    value.as_object().expect("visitor args must be an object")
}

fn str_field<'a>(update: &'a Value, key: &str) -> Option<&'a str> {
    update.get(key).and_then(Value::as_str)
}

fn is_delete(update: &Value) -> bool {
    update.get("delete").and_then(Value::as_bool) == Some(true)
}

/// The upstream `data` map (`{ oldName: newName }`) of field/variant renames.
fn renames(update: &Value) -> Vec<(String, String)> {
    update
        .get("data")
        .and_then(Value::as_object)
        .map(|data| {
            data.iter()
                .map(|(from, to)| (from.clone(), to.as_str().unwrap_or_default().to_string()))
                .collect()
        })
        .unwrap_or_default()
}
