//! Cross-language conformance tests: verify the Rust visitors against fixtures
//! produced by the real upstream `@codama/visitors` (TypeScript), mirroring its
//! own test cases.
//!
//! `fixtures/visitors.json` holds `{ visitor, label, args, input, expected }`
//! cases generated by `fixtures/generate.mjs` (see that file to regenerate). For
//! each case we parse `input` and `expected` into a Rust `RootNode`, run the
//! matching Rust visitor decoded from `args`, and compare the result
//! structurally -- so the Rust port must produce the same tree the TypeScript
//! visitor did.
//!
//! Comparing parsed `RootNode`s (not raw JSON) is deliberate: `serde` omits
//! default/empty fields on serialization, so a string compare would diverge even
//! when the trees are identical.

use codama_nodes::{
    DefaultValueStrategy, InstructionInputValueNode, InstructionNode, NodeTrait, PdaLinkNode,
    PdaNode, PdaSeedNode, ProgramNode, RootNode, ValueNode,
};
use codama_visitors::{
    add_pdas, fill_default_pda_seed_values, get_defined_type_histogram, set_struct_default_values,
    unwrap_defined_types_named, unwrap_instruction_args_defined_types, update_accounts,
    update_defined_types, update_instructions, AccountUpdate, DefinedTypeUpdate,
    InstructionAccountUpdate, InstructionArgumentUpdate, InstructionUpdate, LinkableDictionary,
    StructDefaultValue, TransformVisitor,
};
use pretty_assertions::assert_eq;
use serde::Deserialize;
use serde_json::Value;
use std::collections::HashMap;

#[derive(Deserialize)]
struct Fixtures {
    visitors: Vec<Case>,
    histogram: Vec<HistogramCase>,
    #[serde(rename = "fillPda")]
    fill_pda: Vec<FillPdaCase>,
}

fn fixtures() -> Fixtures {
    serde_json::from_str(include_str!("fixtures/visitors.json")).expect("parse fixtures")
}

#[derive(Deserialize)]
struct Case {
    visitor: String,
    label: String,
    args: Value,
    input: Value,
    expected: Value,
}

#[derive(Deserialize)]
struct HistogramCase {
    label: String,
    input: Value,
    expected: Value,
}

#[derive(Deserialize)]
struct FillPdaCase {
    label: String,
    program: Value,
    instruction: Value,
    value: Value,
    strict: bool,
    expected: Value,
}

#[derive(Deserialize, PartialEq, Debug)]
#[serde(rename_all = "camelCase")]
struct HistogramEntry {
    directly_as_instruction_args: usize,
    in_accounts: usize,
    in_defined_types: usize,
    in_events: usize,
    in_instruction_args: usize,
    total: usize,
}

#[test]
fn matches_upstream_typescript_visitors() {
    let cases = fixtures().visitors;
    assert!(!cases.is_empty(), "no conformance fixtures found");

    let mut count = 0;
    for case in &cases {
        let id = format!("{}/{}", case.visitor, case.label);
        let input = RootNode::from_json(&case.input.to_string())
            .unwrap_or_else(|e| panic!("[{id}] failed to parse input: {e}"));
        let expected = RootNode::from_json(&case.expected.to_string())
            .unwrap_or_else(|e| panic!("[{id}] failed to parse expected: {e}"));

        let actual = run(&case.visitor, &case.args, input);
        assert_eq!(actual, expected, "conformance mismatch in case `{id}`");
        count += 1;
    }
    println!("verified {count} conformance cases");
}

#[test]
fn histogram_matches_upstream() {
    let cases = fixtures().histogram;
    assert!(!cases.is_empty());
    for case in &cases {
        let root = RootNode::from_json(&case.input.to_string()).expect("parse input");
        let actual: HashMap<String, HistogramEntry> = get_defined_type_histogram(&root)
            .into_iter()
            .map(|(key, e)| {
                (
                    key,
                    HistogramEntry {
                        directly_as_instruction_args: e.directly_as_instruction_args,
                        in_accounts: e.in_accounts,
                        in_defined_types: e.in_defined_types,
                        in_events: e.in_events,
                        in_instruction_args: e.in_instruction_args,
                        total: e.total,
                    },
                )
            })
            .collect();
        let expected: HashMap<String, HistogramEntry> =
            serde_json::from_value(case.expected.clone()).expect("parse expected histogram");
        assert_eq!(actual, expected, "histogram mismatch in `{}`", case.label);
    }
}

#[test]
fn fill_default_pda_seed_values_matches_upstream() {
    let cases = fixtures().fill_pda;
    assert!(!cases.is_empty());
    for case in &cases {
        let program: ProgramNode =
            serde_json::from_value(case.program.clone()).expect("parse program");
        let program_name = program.name.to_string();
        let linkables = LinkableDictionary::from_root(&RootNode::new(program));
        let instruction: InstructionNode =
            serde_json::from_value(case.instruction.clone()).expect("parse instruction");
        let value: InstructionInputValueNode =
            serde_json::from_value(case.value.clone()).expect("parse value");
        let expected: InstructionInputValueNode =
            serde_json::from_value(case.expected.clone()).expect("parse expected");

        let actual = fill_default_pda_seed_values(
            value,
            &instruction,
            &linkables,
            Some(&program_name),
            case.strict,
        )
        .expect("fill should succeed");
        assert_eq!(actual, expected, "fillPda mismatch in `{}`", case.label);
    }
}

/// Dispatches a fixture's `visitor` + `args` to the equivalent Rust visitor.
fn run(visitor: &str, args: &Value, input: RootNode) -> RootNode {
    match visitor {
        "updateAccounts" => update_accounts(account_updates(args)).visit_root(input),
        "updateDefinedTypes" => update_defined_types(defined_type_updates(args)).visit_root(input),
        "updateInstructions" => update_instructions(input, instruction_updates(args)),
        "setStructDefaultValues" => {
            set_struct_default_values(struct_default_values(args)).visit_root(input)
        }
        "unwrapDefinedTypes" => unwrap_defined_types_named(input, string_array(args)),
        "unwrapInstructionArgsDefinedTypes" => unwrap_instruction_args_defined_types(input),
        "addPdas" => add_pdas(pdas_by_program(args)).visit_root(input),
        other => panic!("conformance harness has no Rust mapping for visitor `{other}`"),
    }
}

// ---- shared arg helpers ----

fn object(value: &Value) -> &serde_json::Map<String, Value> {
    value.as_object().expect("visitor args must be an object")
}

fn str_field<'a>(update: &'a Value, key: &str) -> Option<&'a str> {
    update.get(key).and_then(Value::as_str)
}

fn is_delete(update: &Value) -> bool {
    update.get("delete").and_then(Value::as_bool) == Some(true)
}

fn renames(update: &Value) -> Vec<(String, String)> {
    update
        .get("data")
        .and_then(Value::as_object)
        .map(|data| {
            data.iter()
                .map(|(from, to)| (from.clone(), to.as_str().unwrap_or_default().to_string()))
                .collect()
        })
        .unwrap_or_default()
}

fn strategy(name: &str) -> Option<DefaultValueStrategy> {
    match name {
        "omitted" => Some(DefaultValueStrategy::Omitted),
        "optional" => Some(DefaultValueStrategy::Optional),
        _ => None,
    }
}

fn string_array(args: &Value) -> Vec<String> {
    args.as_array()
        .expect("args must be an array of strings")
        .iter()
        .filter_map(|v| v.as_str().map(String::from))
        .collect()
}

// ---- per-visitor decoders ----

fn account_updates(args: &Value) -> Vec<(String, AccountUpdate)> {
    object(args)
        .iter()
        .map(|(selector, update)| {
            let mut u = AccountUpdate::new();
            if let Some(name) = str_field(update, "name") {
                u = u.name(name);
            }
            if let Some(size) = update.get("size").and_then(Value::as_u64) {
                u = u.size(size);
            }
            if is_delete(update) {
                u = u.delete();
            }
            for (from, to) in renames(update) {
                u = u.rename(from, to);
            }
            if let Some(seeds) = update.get("seeds") {
                if let Ok(seeds) = serde_json::from_value::<Vec<PdaSeedNode>>(seeds.clone()) {
                    u = u.seeds(seeds);
                }
            }
            if let Some(pda) = update.get("pda") {
                if let Ok(pda) = serde_json::from_value::<PdaLinkNode>(pda.clone()) {
                    u = u.pda(pda);
                }
            }
            (selector.clone(), u)
        })
        .collect()
}

fn defined_type_updates(args: &Value) -> Vec<(String, DefinedTypeUpdate)> {
    object(args)
        .iter()
        .map(|(selector, update)| {
            let mut u = DefinedTypeUpdate::new();
            if let Some(name) = str_field(update, "name") {
                u = u.name(name);
            }
            if is_delete(update) {
                u = u.delete();
            }
            for (from, to) in renames(update) {
                u = u.rename(from, to);
            }
            (selector.clone(), u)
        })
        .collect()
}

fn instruction_updates(args: &Value) -> Vec<(String, InstructionUpdate)> {
    object(args)
        .iter()
        .map(|(selector, update)| {
            let mut u = InstructionUpdate::new();
            if let Some(name) = str_field(update, "name") {
                u = u.name(name);
            }
            if is_delete(update) {
                u = u.delete();
            }
            if let Some(accounts) = update.get("accounts").and_then(Value::as_object) {
                for (name, account) in accounts {
                    let mut a = InstructionAccountUpdate::new();
                    if let Some(new_name) = str_field(account, "name") {
                        a = a.name(new_name);
                    }
                    if let Some(writable) = account.get("isWritable").and_then(Value::as_bool) {
                        a = a.writable(writable);
                    }
                    if let Some(optional) = account.get("isOptional").and_then(Value::as_bool) {
                        a = a.optional(optional);
                    }
                    if let Some(dv) = account.get("defaultValue") {
                        if let Ok(dv) =
                            serde_json::from_value::<InstructionInputValueNode>(dv.clone())
                        {
                            a = a.default_value(dv);
                        }
                    }
                    u = u.account(name.clone(), a);
                }
            }
            if let Some(arguments) = update.get("arguments").and_then(Value::as_object) {
                for (name, argument) in arguments {
                    let mut a = InstructionArgumentUpdate::new();
                    if let Some(new_name) = str_field(argument, "name") {
                        a = a.name(new_name);
                    }
                    if let Some(dv) = argument.get("defaultValue") {
                        if let Ok(dv) =
                            serde_json::from_value::<InstructionInputValueNode>(dv.clone())
                        {
                            a = a.default_value(dv);
                        }
                    }
                    if let Some(s) = str_field(argument, "defaultValueStrategy").and_then(strategy)
                    {
                        a = a.default_value_strategy(s);
                    }
                    u = u.argument(name.clone(), a);
                }
            }
            (selector.clone(), u)
        })
        .collect()
}

fn struct_default_values(args: &Value) -> Vec<(String, Vec<(String, StructDefaultValue)>)> {
    object(args)
        .iter()
        .map(|(selector, fields)| {
            let fields = object(fields)
                .iter()
                .map(|(field, default)| {
                    let value = if let Some(s) = default.get("strategy") {
                        let strategy = s.as_str().and_then(strategy);
                        let value: ValueNode = serde_json::from_value(
                            default
                                .get("value")
                                .expect("WithStrategy needs a value")
                                .clone(),
                        )
                        .expect("parse value node");
                        StructDefaultValue::WithStrategy(value, strategy)
                    } else {
                        StructDefaultValue::Value(
                            serde_json::from_value(default.clone()).expect("parse value node"),
                        )
                    };
                    (field.clone(), value)
                })
                .collect();
            (selector.clone(), fields)
        })
        .collect()
}

fn pdas_by_program(args: &Value) -> Vec<(String, Vec<PdaNode>)> {
    object(args)
        .iter()
        .map(|(program, pdas)| {
            let pdas = pdas
                .as_array()
                .expect("pdas must be an array")
                .iter()
                .map(|pda| serde_json::from_value::<PdaNode>(pda.clone()).expect("parse PdaNode"))
                .collect();
            (program.clone(), pdas)
        })
        .collect()
}
