name: Main

on:
  push:
    branches: ["main"]
  pull_request:

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    name: Format and Lint Crates
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Rustup install nightly
        run: rustup toolchain install nightly

      - name: Rustup install rustfmt
        run: rustup component add rustfmt --toolchain nightly

      - name: Run Cargo fmt
        run: cargo +nightly fmt --all -- --check

      - name: Run Cargo clippy
        run: cargo clippy --all-targets --all-features

  test:
    name: Test Crates
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Cargo test
        run: cargo test --all-features
