name: Main

on:
  push:
    branches: ["main"]
  pull_request:

env:
  RUSTFLAGS: "-Dwarnings"
  RUST_TOOLCHAIN: "nightly-2024-11-22"

jobs:
  lint:
    name: Format and Lint Crates
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install Rust Toolchain and Components
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}
          components: clippy, rustfmt

      - name: Run Cargo fmt
        run: cargo +${{ env.RUST_TOOLCHAIN }} fmt --all -- --check

      - name: Run Cargo clippy
        run: cargo +${{ env.RUST_TOOLCHAIN }} clippy --all-targets --all-features

  test:
    name: Test Crates
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Cargo test
        run: cargo test --all-features
